### ISSUE TITLE
Enhancement Request: Update files.js Split Function for Linux Compatibility

### ISSUE THREAD

**Issue by RomanY467** [christophe77/node-ftp-honeypot#1]
I've identified an issue regarding the compatibility of the current files.js split function on Linux systems. The current implementation splits paths using "\\" as the delimiter, which is not suitable for Linux environments, where the standard path delimiter is "/".
(Tested on Parrot OS arm)

It would be beneficial to make a change in the code or mention this in the README to ensure compatibility with Linux systems.

**Comment by chbellec** [comment]
> I've identified an issue regarding the compatibility of the current files.js split function on Linux systems. The current implementation splits paths using "\" as the delimiter, which is not suitable for Linux environments, where the standard path delimiter is "/". (Tested on Parrot OS arm)
> 
> It would be beneficial to make a change in the code or mention this in the README to ensure compatibility with Linux systems.

Thank you, I'll fix this compatibility issue quickly and I'll let you know.

**Comment by christophe77** [comment]
> I've identified an issue regarding the compatibility of the current files.js split function on Linux systems. The current implementation splits paths using "\" as the delimiter, which is not suitable for Linux environments, where the standard path delimiter is "/". (Tested on Parrot OS arm)
> 
> It would be beneficial to make a change in the code or mention this in the README to ensure compatibility with Linux systems.

Thank you, I'll fix this compatibility issue quickly and I'll let you know.

**Comment by christophe77** [comment]
I made a change, can you upgrade to 1.0.2 and tell me if it's working? I don't have a linux environment right now.

**Comment by RomanY467** [comment]
Works fine now!
